create table dim_viagem (
	cod_viagem INT PRIMARY KEY,
	origem VARCHAR(19),
	destino VARCHAR(19),
	valor DECIMAL(6,2),
	classe VARCHAR(16)
);
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (1, 'Mato Grosso do Sul', 'São Paulo', 575.8, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (2, 'Maranhão', 'Federal', 539.23, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (3, 'Federal', 'Rio de Janeiro', 964.35, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (4, 'Rondônia', 'Goiás', 600.26, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (5, 'Rondônia', 'Espírito Santo', 706.82, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (6, 'Alagoas', 'Federal', 768.64, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (7, 'Tocantins', 'Acre', 742.51, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (8, 'Goiás', 'Rio Grande do Sul', 956.25, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (9, 'Rio Grande do Sul', 'Amazonas', 968.92, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (10, 'Paraná', 'Goiás', 626.05, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (11, 'Rio Grande do Sul', 'Amazonas', 586.02, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (12, 'Pernambuco', 'Distrito', 835.72, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (13, 'Alagoas', 'Espírito Santo', 848.33, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (14, 'Pernambuco', 'Minas Gerais', 697.67, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (15, 'Rio Grande do Sul', 'Maranhão', 824.22, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (16, 'Paraíba', 'Rio de Janeiro', 953.4, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (17, 'Maranhão', 'Distrito', 985.97, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (18, 'Paraná', 'Maranhão', 580.21, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (19, 'Bahia', 'Paraná', 502.27, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (20, 'Alagoas', 'Minas Gerais', 838.1, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (21, 'Pará', 'Pará', 770.05, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (22, 'Tocantins', 'Goiás', 888.48, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (23, 'Paraná', 'Alagoas', 582.44, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (24, 'Pará', 'Santa Catarina', 905.85, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (25, 'Alagoas', 'Maranhão', 886.45, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (26, 'Acre', 'Pará', 519.22, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (27, 'Ceará', 'Mato Grosso do Sul', 609.06, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (28, 'Tocantins', 'Acre', 867.3, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (29, 'Sergipe', 'Alagoas', 730.17, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (30, 'São Paulo', 'Pernambuco', 623.41, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (31, 'Mato Grosso do Sul', 'Piauí', 692.7, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (32, 'Rio Grande do Norte', 'Santa Catarina', 852.9, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (33, 'Pará', 'Tocantins', 725.53, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (34, 'Paraná', 'Amapá', 823.66, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (35, 'Rondônia', 'Tocantins', 857.43, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (36, 'Distrito', 'Paraná', 662.92, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (37, 'Bahia', 'Federal', 816.51, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (38, 'Piauí', 'Mato Grosso', 785.09, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (39, 'Mato Grosso do Sul', 'Acre', 754.59, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (40, 'Rondônia', 'Bahia', 544.14, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (41, 'Rio Grande do Sul', 'Amazonas', 795.97, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (42, 'Rio Grande do Norte', 'Rondônia', 674.9, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (43, 'Alagoas', 'Pernambuco', 868.38, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (44, 'Rondônia', 'Minas Gerais', 954.04, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (45, 'Espírito Santo', 'Goiás', 919.81, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (46, 'Paraná', 'Paraíba', 921.26, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (47, 'Alagoas', 'Goiás', 906.37, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (48, 'Pará', 'Rio de Janeiro', 768.38, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (49, 'Espírito Santo', 'Alagoas', 834.7, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (50, 'Amapá', 'Alagoas', 718.63, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (51, 'Tocantins', 'Amapá', 934.95, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (52, 'Pará', 'Sergipe', 964.76, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (53, 'Paraná', 'Maranhão', 811.32, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (54, 'Rio Grande do Norte', 'Paraná', 541.25, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (55, 'Paraíba', 'Sergipe', 934.05, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (56, 'São Paulo', 'Alagoas', 746.05, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (57, 'Piauí', 'Espírito Santo', 544.4, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (58, 'Minas Gerais', 'São Paulo', 725.41, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (59, 'Rio Grande do Sul', 'Paraná', 761.97, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (60, 'Santa Catarina', 'Rio de Janeiro', 859.07, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (61, 'Acre', 'Ceará', 993.35, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (62, 'Pará', 'Ceará', 600.92, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (63, 'Minas Gerais', 'Amapá', 737.17, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (64, 'Amapá', 'Bahia', 775.5, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (65, 'Rio de Janeiro', 'Santa Catarina', 893.33, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (66, 'Roraima', 'Ceará', 901.26, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (67, 'Bahia', 'Amazonas', 652.88, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (68, 'Maranhão', 'Federal', 510.38, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (69, 'São Paulo', 'Mato Grosso do Sul', 600.3, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (70, 'Mato Grosso do Sul', 'Rio de Janeiro', 608.72, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (71, 'Rondônia', 'São Paulo', 956.74, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (72, 'Pará', 'Rio Grande do Norte', 904.02, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (73, 'Pernambuco', 'Acre', 588.25, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (74, 'Rio Grande do Norte', 'Tocantins', 930.09, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (75, 'Pará', 'Alagoas', 983.04, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (76, 'Pará', 'São Paulo', 938.72, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (77, 'Rio Grande do Sul', 'Bahia', 783.89, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (78, 'Roraima', 'Bahia', 610.95, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (79, 'Ceará', 'Mato Grosso do Sul', 659.71, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (80, 'Espírito Santo', 'Tocantins', 998.65, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (81, 'Maranhão', 'Pernambuco', 768.43, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (82, 'Roraima', 'Piauí', 830.64, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (83, 'Alagoas', 'Alagoas', 879.27, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (84, 'Pará', 'Amapá', 984.28, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (85, 'Bahia', 'Goiás', 910.03, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (86, 'Bahia', 'Acre', 857.71, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (87, 'São Paulo', 'Paraná', 837.56, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (88, 'Ceará', 'Paraíba', 845.72, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (89, 'Piauí', 'Alagoas', 670.4, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (90, 'Federal', 'Amapá', 802.18, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (91, 'São Paulo', 'Amazonas', 854.08, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (92, 'Maranhão', 'Roraima', 729.67, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (93, 'Distrito', 'Amapá', 554.74, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (94, 'Espírito Santo', 'Alagoas', 715.9, 'Primeira Classe');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (95, 'Santa Catarina', 'Minas Gerais', 508.93, 'Classe Econômica');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (96, 'Rio Grande do Sul', 'Amazonas', 522.7, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (97, 'Maranhão', 'Pará', 632.52, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (98, 'Piauí', 'Rio de Janeiro', 583.84, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (99, 'Ceará', 'Rio Grande do Norte', 912.46, 'Classe Executiva');
insert into dim_viagem (cod_viagem, origem, destino, valor, classe) values (100, 'Rio de Janeiro', 'Acre', 536.21, 'Classe Econômica');