create table dim_cliente (
	cod_cliente INT PRIMARY KEY,
	nome VARCHAR(50),
	dt_nascimento DATE,
	genero VARCHAR(9),
	endereco VARCHAR(50)
);
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (1, 'Storm', '13/01/1981', 'Feminino', '21 Ridge Oak Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (2, 'Greggory', '23/07/1996', 'Feminino', '123 Schiller Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (3, 'Charlot', '28/11/1994', 'Feminino', '9615 Derek Street');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (4, 'Ermina', '10/09/2001', 'Feminino', '03 Loomis Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (5, 'Cassondra', '07/07/1997', 'Feminino', '418 Algoma Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (6, 'Mireille', '02/02/1977', 'Feminino', '6939 Golf Course Circle');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (7, 'Colline', '18/10/1991', 'Feminino', '1634 Cardinal Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (8, 'Karlik', '13/01/1971', 'Feminino', '9697 Union Terrace');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (9, 'Sarita', '26/03/1981', 'Feminino', '45 Sloan Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (10, 'Freida', '14/03/1978', 'Feminino', '8359 Mandrake Pass');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (11, 'Aubrey', '15/03/1976', 'Feminino', '68055 Valley Edge Road');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (12, 'Catherine', '10/06/1974', 'Feminino', '057 Knutson Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (13, 'Staci', '25/08/1995', 'Masculino', '09 Moose Hill');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (14, 'Tammi', '05/08/2004', 'Masculino', '93703 Ridge Oak Terrace');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (15, 'Christyna', '26/05/1972', 'Masculino', '20880 Kropf Center');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (16, 'Mack', '12/05/1979', 'Masculino', '35359 Mitchell Alley');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (17, 'Burk', '06/06/1981', 'Masculino', '4789 Lindbergh Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (18, 'Corrie', '20/09/1985', 'Feminino', '8 Carberry Crossing');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (19, 'Vanni', '03/06/1975', 'Feminino', '9 Shasta Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (20, 'Karrah', '31/10/1987', 'Masculino', '247 Toban Circle');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (21, 'Florence', '02/09/1976', 'Feminino', '62 Heffernan Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (22, 'Lonnard', '29/07/1999', 'Masculino', '58139 Moulton Place');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (23, 'Augy', '31/01/1991', 'Feminino', '89199 Clemons Center');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (24, 'Bennie', '08/07/1977', 'Masculino', '95386 Mcbride Drive');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (25, 'Elaine', '03/01/2004', 'Feminino', '653 Haas Crossing');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (26, 'Panchito', '01/09/2001', 'Feminino', '47628 Jackson Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (27, 'Torrey', '19/01/1978', 'Masculino', '623 Myrtle Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (28, 'Johnath', '16/01/1990', 'Feminino', '20 Longview Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (29, 'Aida', '12/09/1971', 'Masculino', '010 Redwing Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (30, 'Berkie', '07/09/1985', 'Masculino', '29 Loomis Terrace');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (31, 'Daveta', '20/08/1995', 'Masculino', '0 Fairview Hill');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (32, 'Sly', '04/12/1980', 'Feminino', '04 Susan Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (33, 'Evyn', '04/06/1992', 'Masculino', '6 Loomis Street');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (34, 'Lotty', '18/05/1978', 'Feminino', '99 Dottie Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (35, 'Baxie', '22/02/2001', 'Feminino', '5128 Farwell Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (36, 'Donetta', '10/02/1984', 'Feminino', '3 Heffernan Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (37, 'Darcie', '23/06/1980', 'Feminino', '024 Anthes Plaza');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (38, 'Burlie', '19/08/1998', 'Feminino', '33 Del Mar Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (39, 'Nicholas', '07/03/1976', 'Masculino', '14 Declaration Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (40, 'Grete', '14/05/1972', 'Masculino', '5 Ludington Pass');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (41, 'Dewey', '12/09/1990', 'Masculino', '525 Loftsgordon Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (42, 'Pen', '08/12/1993', 'Masculino', '86 Tennyson Street');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (43, 'Wolfy', '15/10/1987', 'Masculino', '0816 Toban Alley');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (44, 'Noelyn', '27/11/1990', 'Feminino', '09 Meadow Valley Pass');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (45, 'Tuckie', '16/03/1993', 'Feminino', '85 Crescent Oaks Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (46, 'Nicoli', '18/08/2004', 'Masculino', '582 Sheridan Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (47, 'Cari', '12/05/1990', 'Feminino', '6 Sage Road');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (48, 'Kitti', '19/12/1999', 'Feminino', '25362 Lawn Crossing');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (49, 'Basile', '20/08/1999', 'Feminino', '033 Dryden Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (50, 'Alexio', '06/03/1995', 'Feminino', '38476 2nd Place');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (51, 'Maure', '29/10/1972', 'Feminino', '85476 Messerschmidt Junction');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (52, 'Reine', '10/06/2002', 'Feminino', '03 Scott Hill');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (53, 'Nadean', '12/11/1998', 'Masculino', '8 Carberry Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (54, 'Edward', '31/08/2001', 'Feminino', '7392 Hollow Ridge Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (55, 'Merrel', '10/05/1981', 'Masculino', '84978 Prairieview Alley');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (56, 'Court', '22/01/1970', 'Feminino', '479 Blackbird Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (57, 'Erwin', '14/08/1985', 'Feminino', '20605 Pankratz Street');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (58, 'Gloria', '31/10/1993', 'Masculino', '79568 Calypso Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (59, 'Raviv', '20/02/1971', 'Feminino', '357 Village Junction');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (60, 'Fianna', '07/11/2004', 'Masculino', '67861 2nd Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (61, 'Gloriana', '31/12/1984', 'Feminino', '13928 3rd Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (62, 'Donalt', '25/01/1972', 'Feminino', '40131 Gulseth Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (63, 'Benji', '11/05/1973', 'Masculino', '05 Sunfield Drive');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (64, 'Elston', '24/12/2000', 'Masculino', '55 Thompson Pass');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (65, 'Margit', '01/02/1985', 'Feminino', '10714 Stephen Place');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (66, 'Herc', '06/03/1985', 'Feminino', '9 Golf Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (67, 'Neal', '11/07/1988', 'Feminino', '39 Northland Junction');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (68, 'Dniren', '01/10/1995', 'Masculino', '65644 Hollow Ridge Crossing');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (69, 'Andie', '09/07/1979', 'Masculino', '1 Delaware Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (70, 'Simona', '07/06/1982', 'Feminino', '23825 Karstens Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (71, 'Shelli', '22/10/1976', 'Feminino', '823 Arkansas Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (72, 'Suzi', '20/02/1983', 'Masculino', '8219 Thackeray Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (73, 'Augustin', '16/03/1971', 'Masculino', '6 Village Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (74, 'Fayth', '26/10/1995', 'Masculino', '5870 Little Fleur Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (75, 'Wynn', '02/03/1999', 'Feminino', '99 Continental Circle');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (76, 'Rosalyn', '01/12/1974', 'Feminino', '292 Sunbrook Hill');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (77, 'Adriena', '28/09/1997', 'Feminino', '0 Ruskin Point');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (78, 'Catharine', '18/03/1981', 'Masculino', '3 Kings Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (79, 'Kienan', '11/04/1983', 'Masculino', '04 Towne Center');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (80, 'Tracie', '01/07/1976', 'Masculino', '71 Messerschmidt Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (81, 'Pate', '10/10/1978', 'Masculino', '18209 Dunning Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (82, 'Tonnie', '30/11/1970', 'Masculino', '19018 Stoughton Road');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (83, 'Baxie', '07/06/2003', 'Feminino', '94 Oakridge Junction');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (84, 'Amie', '11/03/2000', 'Masculino', '1674 Scofield Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (85, 'Guglielma', '27/06/1975', 'Masculino', '48488 Lakewood Parkway');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (86, 'Sharline', '19/12/1985', 'Feminino', '3282 Grover Road');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (87, 'Basil', '21/08/1983', 'Masculino', '8 Brentwood Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (88, 'Corby', '29/08/1996', 'Masculino', '9 Texas Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (89, 'Dedie', '18/05/1998', 'Feminino', '0577 Linden Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (90, 'Dominick', '28/12/1981', 'Feminino', '94 Dwight Court');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (91, 'Zed', '28/08/1972', 'Masculino', '22 International Place');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (92, 'Lela', '07/02/1985', 'Feminino', '0016 Hermina Lane');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (93, 'Gilemette', '21/12/1982', 'Feminino', '56 Lunder Trail');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (94, 'Lemar', '30/01/1997', 'Masculino', '504 Jackson Crossing');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (95, 'Gaye', '20/10/1984', 'Feminino', '739 Eliot Center');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (96, 'Garry', '31/07/1979', 'Masculino', '73 Division Way');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (97, 'Carolynn', '17/04/1970', 'Feminino', '01325 Vera Park');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (98, 'Burg', '13/06/1990', 'Feminino', '13 John Wall Avenue');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (99, 'Hakeem', '13/09/1973', 'Feminino', '12625 Loomis Street');
insert into dim_cliente (cod_cliente, nome, dt_nascimento, genero, endereco) values (100, 'Randolph', '05/09/1988', 'Feminino', '07 Moland Avenue');
